### ISSUE TITLE
support fontawesome

### ISSUE THREAD

**Issue by Coernel82** [ralberth/MMM-MysqlQuery#16]
Now having the module running I have a nice idea for styling:

by using the config ``{ name: "level", title: "Fill level cistern", precision: 2,  cssClass: "fa-solid fa-water", suffix: "%"},`` it is possible to show a font awesome icon before the number however the class is applied to the whole line so the font of the data is not the standard font any more.

The workaround would be this:
Apply a custom cssClass ``{ name: "level", title: "Fill level cistern", precision: 2,  cssClass: "cistern", suffix: "%"},`` 
```css
.cistern::before {
	font-family: "Font Awesome 6 Free";
	content: "\f773 \0020"; /* f773 is the font awesome charcter 0020 is a space */
	font-weight: 900;  /* if not using this it will fail! */
}
```

However when you are developing your module further this would be an option to add!
